
import assert from "node:assert/strict";
import { createDrawingHistory, createOfflineQueue, operationsSinceKnown } from "./drawing-fixes.js";

const history = createDrawingHistory();
const stroke = (id) => ({ id, uid: "u1", points: [{ x: 1, y: 1 }, { x: 5, y: 5 }] });
assert.equal(history.undo(), null);
history.add(stroke("one"));
history.add(stroke("two"));
assert.equal(history.undo().stroke.id, "two");
assert.deepEqual(history.strokes.map(s => s.id), ["one"]);
assert.equal(history.redo().id, "two");
assert.deepEqual(history.strokes.map(s => s.id), ["one", "two"]);
history.clear();
assert.equal(history.strokes.length, 0);
assert.equal(history.undo().type, "restore");
assert.deepEqual(history.strokes.map(s => s.id), ["one", "two"]);
assert.equal(history.undo().stroke.id, "two");
assert.equal(history.redo().id, "two");
const bounded = createDrawingHistory(2);
bounded.add(stroke("a"));
bounded.add(stroke("b"));
bounded.add(stroke("c"));
assert.deepEqual([bounded.undo().stroke.id, bounded.undo().stroke.id], ["c", "b"]);
assert.equal(bounded.undo(), null);
const clearHistory = createDrawingHistory();
clearHistory.add(stroke("kept"));
clearHistory.clear();
clearHistory.add(stroke("new"));
assert.equal(clearHistory.undo().stroke.id, "new");
assert.equal(clearHistory.undo(), null);
history.applyUndo("one");
assert.deepEqual(history.strokes.map(s => s.id), ["two"]);
const clearSnapshotHistory = createDrawingHistory();
clearSnapshotHistory.add(stroke("saved-before-clear"));
clearSnapshotHistory.clear();
clearSnapshotHistory.setClearedSnapshot([stroke("saved-before-clear")]);
assert.equal(clearSnapshotHistory.canRestoreClear, true);
assert.deepEqual(clearSnapshotHistory.restoreClearSnapshot().map(s => s.id), ["saved-before-clear"]);
assert.equal(clearSnapshotHistory.canRestoreClear, false);

const memory = new Map();
const storage = { getItem: key => memory.get(key) ?? null, setItem: (key, value) => memory.set(key, value) };
const queue = createOfflineQueue("partner", storage);
queue.add({ id: "operation-1", type: "stroke" });
assert.equal(queue.length, 1);
assert.equal(createOfflineQueue("partner", storage).length, 1);
queue.remove("operation-1");
assert.equal(queue.length, 0);
assert.deepEqual(operationsSinceKnown({ a: { type: "stroke" }, b: { type: "clear" } }, new Set(["a"])), [{ key: "b", type: "clear" }]);
console.log("Drawing undo/redo, clear restore, and offline outbox tests passed.");
