name = "telegram-photo-proxy"
main = "worker.js"
compatibility_date = "2025-01-01"

[vars]
FIREBASE_PROJECT_ID = "our-little-world-e9cbb"

[[kv_namespaces]]
binding = "PHOTOS"
id = "0b40cea6a99b48f8996a38b938650eda"
